--USE movies

--(SELECT STARNAME
--FROM STARSIN
--WHERE MOVIETITLE = 'Terms of Endearment')
--INTERSECT
--(SELECT NAME
--FROM MOVIESTAR
--WHErE GENDER = 'M');

--SELECT DISTINCT STARNAME
--FROM STARSIN
--INNER JOIN 
--(SELECT TITLE
--FROM MOVIE
--WHERE STUDIONAME = 'MGM') AS movie
--ON STARSIN.MOVIETITLE = movie.TITLE
--WHERE MOVIEYEAR = '1995';

--SELECT DISTINCT NAME
--FROM MOVIEEXEC
--INNER JOIN 
--(SELECT PRODUCERC#
--FROM MOVIE
--WHERE STUDIONAME = 'MGM') AS producer
--ON PRODUCERC# = CERT#;

--SELECT DISTINCT NAME
--FROM MOVIEEXEC, MOVIE
--WHERE STUDIONAME = 'MGM' AND PRODUCERC# = CERT#;

--SELECT TITLE
--FROM MOVIE
--	JOIN (SELECT LENGTH
--			FROM MOVIE AS movie
--			WHERE movie.TITLE = 'Star Wars') AS length
--	ON MOVIE.LENGTH > length.LENGTH;

--SELECT TITLE
--FROM MOVIE
--WHERE LENGTH > (SELECT LENGTH
--				FROM MOVIE AS mov
--				WHERE mov.TITLE = 'Star Wars');

--SELECT a.NAME
--FROM MOVIEEXEC AS a
--	JOIN MOVIEEXEC AS b ON a.NETWORTH > b.NETWORTH AND b.NAME = 'Merv Griffin';

--SELECT TITLE
--FROM MOVIE, MOVIEEXEC
--WHERE PRODUCERC# = CERT#
--	AND MOVIEEXEC.NETWORTH > (SELECT NETWORTH
--								FROM MOVIEEXEC
--								WHERE NAME = 'Merv Griffin');

--SELECT TITLE
--FROM MOVIE JOIN MOVIEEXEC ON PRODUCERC# = CERT#
--				AND NETWORTH > (SELECT NETWORTH
--								FROM MOVIEEXEC
--								WHERE NAME = 'Merv Griffin');


USE PC

SELECT maker, speed
FROM laptop, product
WHERE laptop.model = product.model AND laptop.hd >= 9;

SELECT products.model, products.price
FROM 
((SELECT model, price
FROM laptop)
UNION
(SELECT model, price
FROM pc)
UNION
(SELECT model, price
FROM printer)) AS products
JOIN product ON (product.maker = 'B'
				AND product.model = products.model);

SELECT DISTINCT pc1.hd
FROM pc AS pc1
JOIN pc AS pc2 ON (pc1.code <> pc2.code AND pc1.hd = pc2.hd);

SELECT DISTINCT hd
FROM pc AS pc1
WHERE EXISTS (SELECT hd
				FROM pc AS pc2
				WHERE pc1.hd = pc2.hd AND pc1.code <> pc2.code);

SELECT DISTINCT pc1.model, pc2.model
FROM pc AS pc1, pc AS pc2
WHERE pc1.speed = pc2.speed AND pc1.hd = pc2.hd AND pc1.code <> pc2.code;

SELECT maker
FROM pc, product
WHERE pc.model = product.model;



USE ships

SELECT NAME
FROM CLASSES, SHIPS
WHERE CLASSES.CLASS = SHIPS.CLASS AND DISPLACEMENT > 50000;

SELECT SHIPS.NAME, DISPLACEMENT, NUMGUNS
FROM CLASSES, SHIPS
JOIN OUTCOMES ON BATTLE = 'Guadalcanal' AND SHIPS.NAME = OUTCOMES.SHIP
WHERE CLASSES.CLASS = SHIPS.CLASS;

SELECT DISTINCT COUNTRY
FROM CLASSES AS class1
WHERE class1.TYPE = 'bb' AND EXISTS(SElECT CLASS
								FROM CLASSES
								WHERE CLASSES.TYPE = 'bc' AND class1.COUNTRY = CLASSES.COUNTRY);
								
SELECT OUTCOMES.SHIP
FROM OUTCOMES
JOIN BATTLES ON (BATTLES.NAME = OUTCOMES.BATTLE AND EXISTS(SELECT bat.NAME
															FROM BATTLES AS bat
															WHERE bat.DATE > BATTLES.DATE))
WHERE OUTCOMES.RESULT = 'damaged';


SELECT OUTCOMES.SHIP
FROM OUTCOMES, BATTLES
WHERE OUTCOMES.RESULT = 'damaged' 
					AND OUTCOMES.BATTLE = BATTLES.NAME 
					AND EXISTS(SELECT *
								FROM BATTLES AS bat
								WHERE bat.DATE > BATTLEs.DATE);
								  








