--USE movies
--SELECT ADDRESS
--FROM STUDIO
--WHERE NAME = 'MGM';

--SELECT BIRTHDATE
--FROM MOVIESTAR
--WHERE NAME = 'Sandra Bullock';

--SELECT STARNAME
--FROM STARSIN
--WHERE MOVIEYEAR = 1980 
--			AND MOVIETITLE LIKE '%Empire%';

--SELECT NAME
--FROM MOVIEEXEC
--WHERE NETWORTH > 10000000;

--SELECT NAME
--FROM MOVIESTAR
--WHERE ADDRESS = 'Prefect Rd' OR GENDER = 'M';


--USE pc
--SELECT model, speed AS MHz, hd AS GB
--FROM pc
--WHERE price < 1200;

--SELECT DISTINCT maker
--FROM product
--WHERE type = 'printer';

--SELECT model, ram, screen
--FROM laptop
--WHERE price > 1000;

--SELECT model, speed, hd
--FROM pc
--WHERE (cd = '12x' OR cd = '16x') AND price < 2000;


USE ships
SELECT CLASS, COUNTRY
FROM CLASSES
WHERE NUMGUNS < 10;

SELECT NAME AS shipName
FROM SHIPS
WHERE LAUNCHED < 1918;

SELECT SHIP, BATTLE
FROM OUTCOMES
WHERE RESULT = 'sunk';

SELECT NAME
FROM SHIPS
WHERE NAME= CLASS;

SELECT NAME
FROM SHIPS
WHERE NAME LIKE 'R%';

