USE movies

SELECT NAME, ADDRESS, TITLE, LENGTH
FROM STUDIO, MOVIE
WHERE STUDIO.NAME = MOVIE.STUDIONAME AND YEAR > 1980 AND NAME LIKE 'M%';

SELECT NAME, ADDRESS, MOVIETITLE
FROM MOVIESTAR, STARSIN
WHERE NAME LIKE 'J%' AND NAME = STARNAME AND MOVIEYEAR > 1990;

SELECT TITLE, YEAR, LENGTH
FROM MOVIE
WHERE (LENGTH > 120 OR LENGTH IS NULL) AND YEAR < 2000;

SELECT NAME, GENDER
FROM MOVIESTAR
WHERE NAME LIKE 'J%' AND BIRTHDATE > 1948
ORDER BY NAME DESC;

SELECT STUDIO.NAME, COUNT(STARSIN.STARNAME)
FROM STUDIO, STARSIN, MOVIE
WHERE STUDIO.NAME = MOVIE.STUDIONAME AND MOVIE.TITLE = STARSIN.MOVIETITLE
GROUP BY STUDIO.NAME;

SELECT STARNAME, COUNT(STARSIN.MOVIETITLE) 
FROM STARSIN
GROUP BY STARNAME;

SELECT MOVIE.STUDIONAME, TITLE, MOVIE.YEAR
FROM MOVIE,
(SELECT STUDIONAME, MAX(MOVIE.YEAR) AS YEAR
FROM MOVIE
GROUP BY MOVIE.STUDIONAME) AS mov
WHERE MOVIE.STUDIONAME = mov.STUDIONAME AND MOVIE.YEAR = mov.YEAR;


SELECT STUDIONAME, TITLE, YEAR
FROM MOVIE AS mov
WHERE YEAR = 
(SELECT MAX(MOVIE.YEAR)
FROM MOVIE
WHERE mov.STUDIONAME = MOVIE.STUDIONAME);

SELECT NAME
FROM MOVIESTAR
WHERE GENDER = 'M' AND BIRTHDATE = 
(SELECT MAX(BIRTHDATE)
FROM MOVIESTAR
WHERE GENDER = 'M');

SELECT STUDIONAME, STARNAME
FROM STARSIN, MOVIE, 
(SELECT MAX(STARNAME)
FROM STARSIN, MOVIE
WHERE STARSIN.MOVIETITLE = MOVIE.TITÅ);



SELECT STUDIO.NAME, m1.TITLE, STARSIN.STARNAME, COUNT(STARNAME) 
FROM STUDIO, MOVIE AS m1, STARSIN
WHERE STUDIO.NAME = m1.STUDIONAME AND STARSIN.MOVIETITLE = m1.TITLE  
GROUP BY STUDIONAME, STARNAME
HAVING COUNT(STARNAME) >= ALL(SELECT COUNT(STARNAME)
	FROM MOVIE JOIN STARSIN ON TITLE=MOVIETITLE AND YEAR=MOVIEYEAR
	WHERE STUDIONAME=m1.STUDIONAME
	GROUP BY STARNAME);


SELECT MAX(STARNAME)
FROM STUDIO, MOVIE, STARSIN
WHERE STUDIO.NAME = MOVIE.STUDIONAME AND STARSIN.MOVIETITLE = MOVIE.TITLE
GROUP BY STUDIO.NAME


SELECT STUDIONAME, STARNAME, COUNT(STARNAME)q
FROM MOVIE M JOIN STARSIN  ON TITLE=MOVIETITLE AND YEAR=MOVIEYEAR
GROUP BY STUDIONAME,STARNAME
HAVING COUNT(STARNAME)>=ALL(SELECT COUNT(STARNAME)
	FROM MOVIE JOIN STARSIN ON TITLE=MOVIETITLE AND YEAR=MOVIEYEAR
	WHERE STUDIONAME=M.STUDIONAME
	GROUP BY STARNAME);


SELECT DISTINCT STARSIN.STARNAME, MOVIEEXEC.NAME
FROM STARSIN JOIN MOVIE ON STARSIN.MOVIETITLE = MOVIE.TITLE 
JOIN MOVIEEXEC ON MOVIE.PRODUCERC# = MOVIEEXEC.CERT#
WHERE MOVIEEXEC.NETWORTH = (SELECT MAX(NETWORTH)
							FROM MOVIEEXEC)

